name: first_project
description: "List Creator Application"
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.1
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
flutter_icons:
  android: true
  ios: true

  # IOS:
  image_path: "assets/icon/Icon.png"
  # Android:
  adaptive_icon_background: "#0F5CC8"
  adaptive_icon_foreground: "assets/icon/foreground/forerground.png"
  # This will add 32% padding around your image to make it smaller  
  adaptive_icon_foreground_inset: 32

flutter:
  uses-material-design: true